# |>|-------------------------
# |<|   KillinRewards (v0.5.2)
# |>|     Created with <3
# |<|       by dotalw
# |>|-------------------------

# Don't change this value unless you know what you're doing
kill-in-rewards: 0.6

# Modify base permissions
permissions:
  player: "kr.player" # default, ex: kr.player.something

# Customize messages that's sent to killers (players).
# Use %player% to get the killer's name, %target% to get the killed player/entity
# %amount% to get the given/taken amount of money
# supports color codes
messages:
  player-kill-give: "&7You have earned &a&l%amount% &7for killing &a&l%target%"
  player-kill-take: "&7You have lost &c&l%amount% &7for killing &c&l%target%"
  entity-kill-give: "&7You have earned &a&l%amount% &7for killing a &a&l%target%"
  entity-kill-take: "&7You have lost &c&l%amount% &7for killing a &c&l%target%"

# Reward players when killing other players
killin-players:
  enabled: true
  immediate-respawn: true
  reward-money:
    enabled: true
    send-message: true
    amounts: # give players "kr.player.<name>" permission, to get the given amount
      default: 5 # default is given by default to any one.
      vip: 10 # vip requires "kr.player.vip", and so on, you can add more.
  reward-command:
    enabled: false
    commands:
      default:
        - "give %player% minecraft:diamond 1"
        - "give %player% minecraft:iron_ingot 10"
      vip:
        - "give %player% minecraft:diamond 3"
        - "give %player% minecraft:iron_ingot 25"
# Reward players when killing entities
killin-entities:
  enabled: true
  reward-money:
    enabled: true
    send-message: true
    amounts: # give players "kr.player.<name>" permission, to get the given amount
      Zombie:
        default: 5
        vip: 10
      Cow:
        default: -5
        vip: -2
  reward-command:
    enabled: false
    commands:
      Zombie:
        default:
          - "give %player% minecraft:feather 3"
          - "give %player% minecraft:gold_nugget 1"
        vip:
          - "give %player% minecraft:feather 6"
          - "give %player% minecraft:gold_nugget 3"
      Cow:
        default:
          - "give %player% minecraft:bone 3"
        vip:
          - "give %player% minecraft:bone 6"