# Created by dotalw on July 2017.
name: KillinRewards
version: 0.5.2
author: dotalw
main: me.dotalw.KillinRewards.Core
api-version: 1.16
softdepend: [Vault]
permissions:
  kr.player.default:
    default: true
  kr.reload:
    default: op
commands:
  killinrewards:
    description: "KillinRewards main command."
    usage: /<command>
    aliases: [kr, killin-rewards]