# Created by Alw7SHxD on July 2017.
name: KillinRewards
version: 0.5
author: Alw7SHxD
main: me.Alw7SHxD.KillinRewards.Core
softdepend: [Vault]
permissions:
  kr.player.default:
    default: true
  kr.reload:
    default: op
commands:
  killinrewards:
    description: "KillinRewards main command."
    usage: /<command>
    aliases: [kr, killin-rewards]